name: Run audit example
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Install
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: npm install
      - run: npm run depTree
      - run: npm run updates
      - run: npm run audit
